### ISSUE TITLE
.conn File Issue

### ISSUE THREAD

**Issue by quigon236** [Cheenzo/StudioParts#4]
I followed your instructions for creating the CustomParts folder and subfolders. For the .col and .dat files, I was able to view the raw text and save to my computer, and then upload into the appropriate subfolder. The .conn files are only viewable as a download, and my computer doesn't recognize the file type. When I open Studio after adding the custom part, I am not able to place the part in connection with any of the master bricks. I think the problem is with the file type, not sure what I am doing wrong. Any suggestions? I am working on Windows 11.

**Comment by Cheenzo** [comment]
.conn files are not readable files so it is normal that you can only download them from GitHub and that your computer does not recognize this file type that is specific to Studio.

Make sure that for each part you place the files in the appropriate subfolders:
*.conn files go to the connectivity subfolder
*.dat files go to the parts subfolder
*.col files go to the collider subfolder

Then launch Studio and it should work

**Comment by CanePlayz** [comment]
Should this be closed as completed?
